### ISSUE TITLE
[BUG] I downloaded the latest version of silverbullet, But I am not able to open it. I have installed "C++ 2015 Redistributable". When I run the SilverBullet Application file it doesn't do anything. I have tried it by restarting windows but nothing seems to open.

### ISSUE THREAD

**Issue by INSANELYOFFICIAL** [mohamm4dx/SilverBullet#1]
I downloaded the latest version of silverbullet, But I am not able to open it. I have installed "C++ 2015 Redistributable". When I run the SilverBullet Application file it doesn't do anything. I have tried it by restarting windows but nothing seems to open.

**Comment by mohamm4dx** [comment]
You installed both (x64 and x86)?

**Comment by INSANELYOFFICIAL** [comment]
> You installed both (x64 and x86)?

No I didn't installed both (x64 and x86). After reading your comment I installed both and it started working. Thanks.
