### ISSUE TITLE
[BUG] Unable to edit config

### ISSUE THREAD

**Issue by zTr3x** [mohamm4dx/SilverBullet#36]
Creating or editing config crashes the app.

**Comment by carbinegamerz** [comment]
Hey there.. I am here to fix the issue. Open SilverBullet and go to Help<Requirements and there you will find fix CefSharp error. Just click on that and it will redirect you to download Visual C++ Redistributable for Visual Studio 2015, just click on Download and download both x86 and x64 version and install them. Hurrah, your error will be solved!!

**Comment by carbinegamerz** [comment]
Hey there!! I am here to solve your issue. Open SilverBullet and go to Help<Requirements and there click on 'Fix CefSharp error'. Then a website will open to Download 'Visual C++ Redistributable for Visual Studio 2015'. Click on Download and download both x86 and x64 and install them. Then restart SilverBullet and Hurrah! Your error will be fixed!! - By C G
