### ISSUE TITLE
Can't build it properly with VS2017

### ISSUE THREAD

**Issue by willywilly12345** [mohamm4dx/SilverBullet#7]
Hi, I already have installed .NET framework (dev) 4.7.2 and C++ 2015+ Redistributable x64, tried to install both x64 and x86. I am getting this errors:
![Capture](https://user-images.githubusercontent.com/50784250/94175987-b77a8c00-fe97-11ea-91ee-92d78e2a001a.JPG)

**Comment by mahdibland** [comment]
> Hi, I already have installed .NET framework (dev) 4.7.2 and C++ 2015+ Redistributable x64, tried to install both x64 and x86. I am getting this errors:
> ![Capture](https://user-images.githubusercontent.com/50784250/94175987-b77a8c00-fe97-11ea-91ee-92d78e2a001a.JPG)

Rebuild the source to automatically download all missed Dependencies and libraries for you
