### ISSUE TITLE
HOW TO USE SILVERBULLET WITHOUT A COMBOLIST?

### ISSUE THREAD

**Issue by Samsung2023** [mohamm4dx/SilverBullet#82]
I made a config that **don't need combolist** , But silverbullet don't work without a combolist, So I have to choose a random combo to make the config work, But this will **make the config slower** .. Please is there anyway to run a config without a combolist?
or if there is any external function that I can add to svb which makes running configs without a combolist possible.

**Comment by Samsung2023** [comment]
> use a blank one, or edit the code by yourself, also i can give you more help if i can acess to the code for the config
> 
> ឵batman#2642

nvm I know how to do it now

**Comment by wacns** [comment]
> > use a blank one, or edit the code by yourself, also i can give you more help if i can acess to the code for the config
> > ឵batman#2642
> 
> nvm I know how to do it now

how to do it ?

**Comment by Samsung2023** [comment]
> > > use a blank one, or edit the code by yourself, also i can give you more help if i can acess to the code for the config
> > > ឵batman#2642
> > 
> > 
> > nvm I know how to do it now
> 
> how to do it ?

jump
